"""empty message

Revision ID: 37230fc3ec3a
Revises: 8bf04de402a5
Create Date: 2025-07-02 08:42:30.132931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37230fc3ec3a'
down_revision = '8bf04de402a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detallecompra_rifa', schema=None) as batch_op:
        batch_op.alter_column('cantidad',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('importe_total',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detallecompra_rifa', schema=None) as batch_op:
        batch_op.alter_column('importe_total',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('cantidad',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
