"""empty message

Revision ID: 5793280f17cc
Revises: dacb71a6c777
Create Date: 2025-06-10 16:21:12.313985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5793280f17cc'
down_revision = 'dacb71a6c777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rifas', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_rifas_boleto_ganador', 'boleto', ['boleto_ganador'], ['id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rifas', schema=None) as batch_op:
        batch_op.drop_constraint('fk_rifas_boleto_ganador', type_='foreignkey')

    # ### end Alembic commands ###
