"""empty message

Revision ID: 8bf04de402a5
Revises: c519dfff5424
Create Date: 2025-07-02 08:32:10.967704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bf04de402a5'
down_revision = 'c519dfff5424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_compra', schema=None) as batch_op:
        batch_op.alter_column('compra_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_compra', schema=None) as batch_op:
        batch_op.alter_column('compra_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
