"""empty message

Revision ID: 9c722c862aa1
Revises: 37230fc3ec3a
Create Date: 2025-07-02 09:12:28.074853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c722c862aa1'
down_revision = '37230fc3ec3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rifas', schema=None) as batch_op:
        batch_op.drop_constraint('fk_rifas_boleto_ganador', type_='foreignkey')
        batch_op.alter_column('boleto_ganador',
            existing_type=sa.INTEGER(),
            nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rifas', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_rifas_boleto_ganador', 'boleto', ['boleto_ganador'], ['id'])

    # ### end Alembic commands ###
