"""empty message

Revision ID: c519dfff5424
Revises: f5d58b7930fc
Create Date: 2025-07-01 22:04:36.912562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c519dfff5424'
down_revision = 'f5d58b7930fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_compra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_compra', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('num_pedido', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['num_pedido'])


    with op.batch_alter_table('boleto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_pedido', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'detalle_compra', ['num_pedido'], ['num_pedido'])



    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boleto', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('num_pedido')


    with op.batch_alter_table('detalle_compra', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('num_pedido')
        batch_op.drop_column('fecha_compra')



    # ### end Alembic commands ###
