"""empty message

Revision ID: dacb71a6c777
Revises: 
Create Date: 2025-06-09 21:58:57.971630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dacb71a6c777'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('contraseña', sa.String(length=255), nullable=False),
    sa.Column('direccion_envio', sa.String(length=255), nullable=True),
    sa.Column('dni', sa.String(length=20), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('vendedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('persona_contacto', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_compra', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rifas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_rifa', sa.String(length=150), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.Column('fecha_de_sorteo', sa.Date(), nullable=False),
    sa.Column('hora_de_sorteo', sa.Time(), nullable=False),
    sa.Column('precio_boleto', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('premio_rifa', sa.String(length=255), nullable=False),
    sa.Column('url_premio', sa.String(length=255), nullable=True),
    sa.Column('numero_max_boletos', sa.Integer(), nullable=False),
    sa.Column('status_sorteo', sa.String(length=50), nullable=False),
    sa.Column('boleto_ganador', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['boleto_ganador'], ['boleto.id'], name='fk_rifas_boleto_ganador', use_alter=True),
    sa.ForeignKeyConstraint(['vendedor_id'], ['vendedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boleto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rifa_id', sa.Integer(), nullable=False),
    sa.Column('confirmado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rifa_id'], ['rifas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('compra_id', sa.Integer(), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.Column('stripe_session_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['compra_id'], ['compra.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['vendedor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('compra_id', name='uq_compra_detalle')
    )
    op.create_table('detallecompra_rifa',
    sa.Column('detalle_compra_id', sa.Integer(), nullable=False),
    sa.Column('rifa_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('importe_total', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['detalle_compra_id'], ['detalle_compra.id'], ),
    sa.ForeignKeyConstraint(['rifa_id'], ['rifas.id'], ),
    sa.PrimaryKeyConstraint('detalle_compra_id', 'rifa_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detallecompra_rifa')
    op.drop_table('detalle_compra')
    op.drop_table('boleto')
    op.drop_table('rifas')
    op.drop_table('compra')
    op.drop_table('vendedor')
    op.drop_table('usuario')
    # ### end Alembic commands ###
