"""empty message

Revision ID: f5d58b7930fc
Revises: 5793280f17cc
Create Date: 2025-06-24 11:05:18.890522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5d58b7930fc'
down_revision = '5793280f17cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_compra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('importe_total', sa.DECIMAL(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('rifas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_boletos_vendidos', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stripe_product_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('stripe_price_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rifas', schema=None) as batch_op:
        batch_op.drop_column('stripe_price_id')
        batch_op.drop_column('stripe_product_id')
        batch_op.drop_column('numero_boletos_vendidos')

    with op.batch_alter_table('detalle_compra', schema=None) as batch_op:
        batch_op.drop_column('importe_total')
        batch_op.drop_column('cantidad')

    # ### end Alembic commands ###
